registration:
  model: gpt-3.5-turbo
  endpoint: CreateCompletion
local_paths:
  model: ggml-gpt4all-j.bin
  template: chat-gpt4all
  backend: gpt4all-j
  threads: 4
request_defaults:
  top_p: 0.7
  temperature: 0.2
  x-localai-extensions:
    top_k: 80